/**
 * Script SQL para crear las nuevas tablas y actualizar las existentes
 * Ejecutar en Supabase SQL Editor
 */

-- ============================================
-- 1. ACTUALIZAR TABLA USERS
-- ============================================

-- Agregar columna user_id para relacionar con auth.users
ALTER TABLE public.users 
ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id);

-- Crear índice para mejorar rendimiento
CREATE INDEX IF NOT EXISTS users_user_id_idx ON public.users(user_id);

-- ============================================
-- 2. CREAR TABLA PURCHASES (COMPRAS)
-- ============================================

CREATE TABLE IF NOT EXISTS public.purchases (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  function_id bigint NOT NULL REFERENCES theatre_functions(id) ON DELETE RESTRICT,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  total_price integer NOT NULL CHECK (total_price >= 0),
  purchase_date timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'completed' CHECK (status IN ('completed', 'pending', 'cancelled')),
  CONSTRAINT purchases_pkey PRIMARY KEY (id)
);

-- Índices para mejorar rendimiento
CREATE INDEX IF NOT EXISTS purchases_user_id_idx ON public.purchases(user_id);
CREATE INDEX IF NOT EXISTS purchases_function_id_idx ON public.purchases(function_id);
CREATE INDEX IF NOT EXISTS purchases_purchase_date_idx ON public.purchases(purchase_date DESC);

-- ============================================
-- 3. HABILITAR ROW LEVEL SECURITY
-- ============================================

-- Habilitar RLS en purchases
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;

-- Policy: Los usuarios pueden ver solo sus propias compras
DROP POLICY IF EXISTS "Users can view own purchases" ON public.purchases;
CREATE POLICY "Users can view own purchases"
  ON public.purchases
  FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: Los usuarios pueden crear compras para sí mismos
DROP POLICY IF EXISTS "Users can create own purchases" ON public.purchases;
CREATE POLICY "Users can create own purchases"
  ON public.purchases
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Policy: Los usuarios pueden actualizar sus propias compras
DROP POLICY IF EXISTS "Users can update own purchases" ON public.purchases;
CREATE POLICY "Users can update own purchases"
  ON public.purchases
  FOR UPDATE
  USING (auth.uid() = user_id);

-- ============================================
-- 4. HABILITAR RLS EN USERS (OPCIONAL)
-- ============================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Policy: Los usuarios pueden ver solo su propio registro
DROP POLICY IF EXISTS "Users can view own data" ON public.users;
CREATE POLICY "Users can view own data"
  ON public.users
  FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: Los usuarios pueden actualizar solo su propio registro
DROP POLICY IF EXISTS "Users can update own data" ON public.users;
CREATE POLICY "Users can update own data"
  ON public.users
  FOR UPDATE
  USING (auth.uid() = user_id);

-- Policy: Permitir insert con user_id del usuario autenticado
DROP POLICY IF EXISTS "Users can insert own data" ON public.users;
CREATE POLICY "Users can insert own data"
  ON public.users
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- ============================================
-- 5. FUNCIÓN HELPER: Obtener compras con detalles
-- ============================================

-- Vista para facilitar consultas de compras con información de funciones
CREATE OR REPLACE VIEW purchases_with_details AS
SELECT 
  p.id,
  p.user_id,
  p.function_id,
  p.quantity,
  p.total_price,
  p.purchase_date,
  p.status,
  f.nombre_funcion,
  f.descripcion_funcion,
  f.imagen_funcion,
  f.valor_entrada_funcion
FROM purchases p
JOIN theatre_functions f ON p.function_id = f.id;

-- Comentarios para documentación
COMMENT ON TABLE public.purchases IS 'Almacena las compras de entradas realizadas por los usuarios';
COMMENT ON COLUMN public.purchases.user_id IS 'ID del usuario que realizó la compra (referencia a auth.users)';
COMMENT ON COLUMN public.purchases.function_id IS 'ID de la función de teatro comprada';
COMMENT ON COLUMN public.purchases.quantity IS 'Cantidad de entradas compradas';
COMMENT ON COLUMN public.purchases.total_price IS 'Precio total de la compra';
COMMENT ON COLUMN public.purchases.status IS 'Estado de la compra: completed, pending, cancelled';
